### ISSUE TITLE
Unicode does not work that way

### ISSUE THREAD

**Issue by rspeer** [mattbierner/underhanded-c-2015#1]
I enjoyed the overall approach, but your justification for the escape sequences in the string, convoluted as it is, doesn't make sense even when you suppose this Bobian language exists.

Unicode has to be in an encoding to be represented as bytes. There isn't an encoding where you can just spell out the codepoints of the characters as bytes in the middle of an otherwise ASCII string. (UTF-16 is not compatible with ASCII and would not be used in C literals for that reason.) So no editor or terminal will display those bytes as 觬巂.

It makes me wonder if you could fix the explanation by finding a valid UTF-8 sequence that accomplishes the underhanded code that you want.

**Comment by mattbierner** [comment]
Thanks. I took another quick look at just the evil string based on your advice. The code and blog post have both been updated.

The error string is now `u"썝 - "` pasted directly into the file, which should be encoded `89 ec 5d c3` (I don't think these are officially mapped in unicode but hopefully the missing character symbol wouldn't raise any flags during code review). I also got rid of the weird nulls characters by using `ret` instead of `ret 0`.
